const travelData = [
  // 2023
  { city: "Singapore", country: "Singapore", lat: 1.3521, lng: 103.8198, year: 2023, description: "Singapore Marathon 2023! Joining the 10k.", image: "assets/img/1.jpg", hoverDescription: "Marina Bay lights ✨", hoverImage: "assets/img/2.jpg" },
  { city: "Genting", country: "Malaysia", lat: 3.4213, lng: 101.7934, year: 2023, description: "Chin Swee Temple vibes above the clouds 🌤️", image: "assets/img/3.jpg", hoverDescription: "Cool mountain escape 🎢", hoverImage: "assets/img/4.jpg" },
  { city: "Kuala Lumpur", country: "Malaysia", lat: 3.1390, lng: 101.6869, year: 2023, description: "Bukit Bintang lights and Christmas glam 🎄✨", image: "assets/img/5.jpg", hoverDescription: "Petronas and street food 🌃", hoverImage: "assets/img/6.jpg" },
  { city: "Ho Chi Minh", country: "Vietnam", lat: 10.7769, lng: 106.7009, year: 2023, description: "Scooter madness in Saigon with Gojek vibes 🛵💨", image: "assets/img/7.jpg", hoverDescription: "Chaotic scooters & pho 🍜", hoverImage: "assets/img/8.jpg" },
  { city: "Hanoi", country: "Vietnam", lat: 21.0285, lng: 105.8542, year: 2023, description: "Chillin’ with avo toast & local coffee ☕🥑", image: "assets/img/9.jpg", hoverDescription: "Old Quarter vibes 🚲", hoverImage: "assets/img/10.jpg" },
  { city: "Sapa", country: "Vietnam", lat: 22.3402, lng: 103.8448, year: 2023, description: "Sapa nights at the iconic Sun Plaza 🌟", image: "assets/img/11.jpg", hoverDescription: "Closer to the clouds than my comfort zone 🌥️ Vietnam’s roof; checked off", hoverImage: "assets/img/12.jpg" },
  { city: "Lao Cai", country: "Vietnam", lat: 22.4856, lng: 103.9707, year: 2023, description: "Cà phê sữa đá moment before the border 🚉", image: "assets/img/13.jpg", hoverDescription: "Border adventures 🚉 Crossing lines, collecting stories 🇻🇳🇨🇳", hoverImage: "assets/img/14.jpg" },

  // 2024
  { city: "Almaty", country: "Kazakhstan", lat: 43.2220, lng: 76.8512, year: 2024, description: "Finished 12K trail run at Tau Jarys! 🏅", image: "assets/img/15.jpg", hoverDescription: "Mountain skyline 🏔️", hoverImage: "assets/img/16.jpg" },
  { city: "Kolsai Lakes", country: "Kazakhstan", lat: 42.9374, lng: 78.3325, year: 2024, description: "Magical morning at Kolsai, totally worth the rain 🌲✨", image: "assets/img/17.jpg", hoverDescription: "Hidden blue lakes 💧", hoverImage: "assets/img/18.jpg" },
  { city: "Charyn Canyon", country: "Kazakhstan", lat: 43.3653, lng: 79.0681, year: 2024, description: "Squad exploring Kazakhstan’s mini Grand Canyon 🏜️", image: "assets/img/19.jpg", hoverDescription: "Mini Grand Canyon 🏜️", hoverImage: "assets/img/20.jpg" },
  { city: "Ankara", country: "Turkey", lat: 39.9334, lng: 32.8597, year: 2024, description: "Hidden alleys of Ankara’s old town 🏘️", image: "assets/img/21.jpg", hoverDescription: "Capital city hustle 🏛️", hoverImage: "assets/img/22.jpg" },
  { city: "Cappadocia", country: "Turkey", lat: 38.6431, lng: 34.8270, year: 2024, description: "Fairy chimneys and alien vibes 🌄", image: "assets/img/23.jpg", hoverDescription: "Hot air balloons 🎈", hoverImage: "assets/img/24.jpg" },
  { city: "Istanbul", country: "Turkey", lat: 41.0082, lng: 28.9784, year: 2024, description: "Chill yacht sunset ride on the Bosphorus 🌅", image: "assets/img/25.jpg", hoverDescription: "Mosques & bazaars 🕌", hoverImage: "assets/img/26.jpg" },
  { city: "Abu Dhabi", country: "UAE", lat: 24.4539, lng: 54.3773, year: 2024, description: "Highway hustle in the desert city 🏎️🌴", image: "assets/img/27.jpg", hoverDescription: "Sheikh Zayed beauty 🤍 Moonlit prayers and golden domes 🌙", hoverImage: "assets/img/28.jpg" },
  { city: "Dubai", country: "UAE", lat: 25.276987, lng: 55.296249, year: 2024, description: "Midnight beach walk under city lights 🌃", image: "assets/img/29.jpg", hoverDescription: "Skyscraper flex 🏙️", hoverImage: "assets/img/30.jpg" },
  { city: "Bali", country: "Indonesia", lat: -8.3405, lng: 115.0920, year: 2024, description: "Post-run buzz at the Maybank Marathon (Joined the 21K) 🥇", image: "assets/img/31.jpg", hoverDescription: "Beach vibes & sunset 🌅", hoverImage: "assets/img/32.jpg" },
  { city: "Padang", country: "Indonesia", lat: -0.9471, lng: 100.4172, year: 2024, description: "Old town charm and rendang cravings 😋", image: "assets/img/33.jpg", hoverDescription: "Unique architecture of Rumah Gadang. Rumah Gadang energy in the city 🇮🇩", hoverImage: "assets/img/34.jpg" },

  // 2025
  { city: "Tokyo", country: "Japan", lat: 35.6895, lng: 139.6917, year: 2025, description: "Neon jungle and endless crossings in Shibuya ✨", image: "assets/img/35.jpg", hoverDescription: "The Tokyo Tower ✨ Towering dreams, neon beams", hoverImage: "assets/img/36.jpg" },
  { city: "Sapporo", country: "Japan", lat: 43.0618, lng: 141.3545, year: 2025, description: "Snowy evenings at Sapporo TV Tower ❄️", image: "assets/img/37.jpg", hoverDescription: "Snow hits different in Hokkaido ❄️", hoverImage: "assets/img/38.jpg" },
  { city: "Niseko", country: "Japan", lat: 42.8048, lng: 140.6874, year: 2025, description: "Strapped in and ready to shred in Niseko 🏂", image: "assets/img/39.jpg", hoverDescription: "Ski heaven ⛷️ &coffee", hoverImage: "assets/img/40.jpg" },
  { city: "Otaru", country: "Japan", lat: 43.1907, lng: 140.9947, year: 2025, description: "Winter strolls in the canal city of Otaru 🌨️", image: "assets/img/41.jpg", hoverDescription: "Canal town magic 🏮", hoverImage: "assets/img/42.jpg" },
  { city: "Asahikawa", country: "Japan", lat: 43.7706, lng: 142.3648, year: 2025, description: "Snowy traffic lights and frozen streets, classic Asahikawa vibes ❄️🚦", image: "assets/img/43.jpg", hoverDescription: "Hokkaido: where even the cold feels warm 🐧", hoverImage: "assets/img/44.jpg" },
  { city: "Furano", country: "Japan", lat: 43.3420, lng: 142.3834, year: 2025, description: "Quirky countryside stops in Furano; retro bus & snowy charm 🚌❄️", image: "assets/img/45.jpg", hoverDescription: "Countryside winter stop 💜 Ningle Terrace", hoverImage: "assets/img/46.jpg" },
  { city: "Biei", country: "Japan", lat: 43.5917, lng: 142.4677, year: 2025, description: "Winter forest magic in Biei, totally frozen and serene 🤍🌲", image: "assets/img/47.jpg", hoverDescription: "Frozen pond scene 🌿 Shirahige", hoverImage: "assets/img/48.jpg" },
  { city: "Wakkanai", country: "Japan", lat: 45.4094, lng: 141.6739, year: 2025, description: "Far north icy winds in Wakkanai; edge of Japan vibes 🌬️🇯🇵", image: "assets/img/49.jpg", hoverDescription: "Northern tip views 🌊", hoverImage: "assets/img/50.jpg" },
  { city: "Fuji", country: "Japan", lat: 35.3606, lng: 138.7274, year: 2025, description: "Chill lavender fields by Lake Kawaguchi, Mt. Fuji backdrop 💜🏔️", image: "assets/img/51.jpg", hoverDescription: "Iconic peak & chill lakes 🗻", hoverImage: "assets/img/52.jpg" },
  { city: "Melbourne", country: "Australia", lat: -37.8136, lng: 144.9631, year: 2025, description: "City sunsets and breezy walks; Melbourne skyline in the glow 🌇🇦🇺", image: "assets/img/53.jpg", hoverDescription: "Laneways & cafes ☕", hoverImage: "assets/img/54.jpg" },
  { city: "Daylesford", country: "Australia", lat: -37.3417, lng: 144.1420, year: 2025, description: "Golden leaves and spa town strolls; Daylesford autumn feels 🍂✨", image: "assets/img/55.jpg", hoverDescription: "Mirror mirror on the lake 💧", hoverImage: "assets/img/56.jpg" },
  { city: "Hobart", country: "Australia", lat: -42.8821, lng: 147.3272, year: 2025, description: "Heritage building lit red, waterfront reflections; Hobart nights ❤️🏛️", image: "assets/img/57.jpg", hoverDescription: "Tasmania from above, life hits different", hoverImage: "assets/img/58.jpg" },
  { city: "Bruny Island", country: "Australia", lat: -43.4236, lng: 147.3317, year: 2025, description: "Epic isthmus views at The Neck; Bruny Island split perfection 🌊🌿", image: "assets/img/59.jpg", hoverDescription: "Oysters & cliffs 🦪", hoverImage: "assets/img/60.jpg" },
  { city: "Eaglehawk", country: "Australia", lat: -43.0257, lng: 147.9574, year: 2025, description: "Sea caves & rugged coastlines; Eaglehawk Neck feels 🌊🪨", image: "assets/img/61.jpg", hoverDescription: "Sea caves & coastlines 🌊 Devils Kitchen", hoverImage: "assets/img/62.jpg" },
];
